### ISSUE TITLE
new command line option /restart

### ISSUE THREAD

**Issue by VMSrefugee** [Rfvgyhn/min-ed-launcher#1]
Loving the new abbreviated launcher!

I'm all for .json, but would it be easy/useful to add /restart as another command line option?

**Comment by Rfvgyhn** [comment]
Currently, all arguments are supported by the default launcher. My stance has been not to add new arguments if the functionality can be placed in the settings file because I don't want run the risk, as unlikely as it may be, of FDev introducing a new argument with the same name but meaning something different.

**Comment by Rfvgyhn** [comment]
Cat's out of the bag now that frontier account support required a new flag that the default launcher doesn't support. 

The config file option has been replaced with the argument `/restart delay`.

Your idea makes it much more convenient to use also. Now you can have a shortcut dedicated to restart mode and only use it when you want the restart functionality.
