### ISSUE TITLE
AVAST Antivirus reports MinEDLauncher.exe as IDP.Generic

### ISSUE THREAD

**Issue by acnicholls** [rfvgyhn/min-ed-launcher#102]
**Describe the bug/error**
My antivirus stops execution of the game and quarantines the executable when I run the game with 3rd party tools.

**Debug log**
Log file with 2 "antivirus detections"
[min-ed-launcher.log](https://github.com/rfvgyhn/min-ed-launcher/files/11713650/min-ed-launcher.log)

Log file with "virus detections" and successful launch (no 3rd party tools)
[min-ed-launcher.log](https://github.com/rfvgyhn/min-ed-launcher/files/11713659/min-ed-launcher.log)

Image of Antivirus Report 
![image](https://github.com/rfvgyhn/min-ed-launcher/assets/5872559/7d890d2f-ccc4-49c7-9cbd-a746f7a40e5c)

**Comment by rfvgyhn** [comment]
Is it any 3rd party tool or just a specific one? If you try to start just Notepad.exe does it also flag it? It could be the case that starting four processes so quickly trips it up.

It _seems_ like [Process.Start](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start) is triggering Avast. The `Process.Start` calls are initiated at [App.fs#421](https://github.com/rfvgyhn/min-ed-launcher/blob/4646842beefcfdf412e295139c8f9eff7148f015/src/MinEdLauncher/App.fs#L421) and [App.fs#422](https://github.com/rfvgyhn/min-ed-launcher/blob/4646842beefcfdf412e295139c8f9eff7148f015/src/MinEdLauncher/App.fs#LL422C17-L422C17).

I'm not sure there's anything I can do about it. It could be a low reputation thing because the launcher is a super niche `exe`. It could be Avast's heuristics creating a false positive. It could be that Avast doesn't like it because it isn't code signed (which I'm not willing to do because of cost).

**Comment by acnicholls** [comment]
I did test with the different 3rd-party tools and one in particular (Elite Odyssey Materials Helper) causes the error, and since it caused the error with the mini launcher, it is now causing the error when I try to run it alone.  the other two apps run perfectly whether manually or from the launcher.

I haven't tried notepad, since the other two tools work.

and I have reported it as best I can at the materials helper github as well
https://github.com/jixxed/ed-odyssey-materials-helper/issues/164

**Comment by acnicholls** [comment]
I got this from the AVAST team, and have tested it, everything is running as it should be

----------------------------
```

AVAST Support <customer.support@avast.com>
	
4:25 AM (18 hours ago)
	
to me

Hello,

Thank you for contacting Avast and reporting a false positive file detection. I'm happy to help.

The reported file was checked by Avast virus specialists and based on the findings the detection was removed. The file is now marked as clean in the Avast virus database. This change may take up to 24 hours to take full effect. Please accept my apology for the inconvenience caused.

If the detection persists after 24 hours, please [update the Avast virus database](https://support.avast.com/article/update-antivirus/) and reply to this email with attached files:

    Take a screenshot of the Avast detection dialog (Threat Secured pop-up with See details - displayed at the bottom).
    A screenshot of the Avast virus database (open Avast Antivirus and go to Menu > About).

For instructions on taking a screenshot, refer to this article: [Creating a screenshot](https://support.avast.com/article/Create-screenshot/).

I hope you have a nice day, and stay safe online.
```
------------------------------

So you can close this ticket.  Sorry for the worry, and thanks for your response to the issue.

keep coding, love the idea of the launcher!
