### ISSUE TITLE
Linux config location is wrong

### ISSUE THREAD

**Issue by infoman** [Rfvgyhn/min-ed-launcher#11]
Instead of properly getting `XDG_CONFIG_HOME` variable, or just using `~/.config` as specified, it creates a directory that is literally named `%XDG_CONFIG_HOME%` inside the game directory and puts `min-ed-launcher/settings.json` there

**Comment by Rfvgyhn** [comment]
I'm not sure what's happening here. `XDG_CONFIG_HOME` is expanded properly on my machine. However, it turns out there are some std lib calls to get the config dir so I switched to that instead of manually parsing stuff. Can you try the [CI build](https://github.com/Rfvgyhn/min-ed-launcher/actions/runs/658845657) and let me know if it works for you.

**Comment by infoman** [comment]
Now it's in `~/.config/min-ed-launcher/min-ed-launcher/settings.json`

**Comment by Rfvgyhn** [comment]
Cool. So the env expansion had to do with a bug in my parsing. Duplicate folder name was due to my sloppy merge conflict. Just pushed a fix.
