### ISSUE TITLE
Shortcuts for Horizons/Odyssey - Epic Games

### ISSUE THREAD

**Issue by ZekeWolf** [rfvgyhn/min-ed-launcher#63]
I have two versions of Odyssey: one through Steam, the other through Epic Games. With help from rfvgyhn, I was able to create separate shortcuts off of my Steam account, one to run Odyssey, the other to run Horizons, both using min-ed-launcher.

Now I want to create a similar set of shortcuts to run the two versions off of my Epic account. Epic allows you to create a shortcut for any installed game. But (unlike shortcuts to Steam games), it doesn't seem to allow me to pass different command line arguments through to the Epic Launcher. This includes /edh and /edo.

If that's a permanent state, I would have to adjust the switches in Settings in the Epic launcher to use min-ed-launcher to run different versions. 

Do you have any suggestions about how to do this? Thank you.

**Comment by rfvgyhn** [comment]
I'm not sure there is a way to do this with the Epic launcher. If you're willing to use [legendary](https://github.com/derrod/legendary) though, you can create a couple .bat files and run those instead. 

Contents of the .bat file would look something like:
`legendary.exe launch 9c203b6ed35846e8a4a9ff1e314f6593 --override-exe MinEdLauncher.exe /autorun /autoquit /edo`

`9c203b6ed35846e8a4a9ff1e314f6593` is Elite's Epic game id.

This would also mean you wouldn't have to overwrite EDLaunch.exe every time the epic store updates the file.

There may be a way to do it with [heroic](https://github.com/Heroic-Games-Launcher/HeroicGa) too (since it's just legendary under the hood) if you'd prefer a GUI. I've never used it though so I'm not sure.

**Comment by ZekeWolf** [comment]
I will try out legendary and report back. Thanks for the suggestion!
