### ISSUE TITLE
Launcher suddenly can't find companion apps defined by settings file

### ISSUE THREAD

**Issue by Razwerkz** [rfvgyhn/min-ed-launcher#89]
When launching companion apps alongside Elite using the Minimal ED Launcher, the launcher suddenly can't find two of my programs.  The apps have not changed in location or filename.

[Log File](https://github.com/rfvgyhn/min-ed-launcher/files/11084222/min-ed-launcher.log) | [Settings File](https://github.com/rfvgyhn/min-ed-launcher/files/11084230/settings.txt) | [ICARUS Terminal GitHub](https://github.com/iaincollins/icarus) | [EDCoPilot Website](https://www.razzafrag.com/) | [Screenshot of Folder Structures](https://user-images.githubusercontent.com/9700289/228101141-7d959280-2416-407b-b111-2ef992a3bfb1.png)

**Comment by rfvgyhn** [comment]
I haven't been able to replicate this. I added a bit more details to the log output but I'm not sure it will help diagnose the issue. You can try the [latest CI build](https://github.com/rfvgyhn/min-ed-launcher/actions/runs/4684674815) (or the next release if it's out) to get the additional debug info.

I assume you're able to launch the apps manually, right? Did this happen after you updated min-ed-launcher or the apps themselves or it just broke without any known changes?

Perhaps there was an environment change after a windows update or something. Maybe the processes won't start because they aren't trusted. Maybe a permissions issue. I'm not really sure.

**Comment by Razwerkz** [comment]
I updated the settings file with another app, and retyped the directories, just in case anything changed that I wasn't aware of.  I have also installed the newest release, and, as I type this post, I no longer have the issue.
